insert into Konto(name,bankleitzahl,kontonummer,betrag,minimum) Values("Max Mustermann","123456","7891012",999111,1);
insert into Konto(name,bankleitzahl,kontonummer,betrag,minimum) Values("Thomas Mller","7891012","123456",500,2);
insert into Markt(name,postleitzahl,adresse,entfernung) Values("REWE","60385","Inheitner str.",1);
insert into Markt(name,postleitzahl,adresse,entfernung) Values("Lidl","60319","Seckbacher ldr.",3);
insert into Markt(name,postleitzahl,adresse,entfernung) Values("Aldi","60318","Seckbacher ldr.",4);
insert into Markt(name,postleitzahl,adresse,entfernung) Values("Penny","60439","Hanauer ldr.",8);
insert into Markt(name,postleitzahl,adresse,entfernung) Values("Metro","60383","Hanauer ldr.",2);
insert into Produkt(name,gewicht,preis) Values("Schokolade",100,1.5);
insert into Produkt(name,gewicht,preis) Values("Cola",1000,1.9);
insert into Produkt(name,gewicht,preis) Values("DVD",0,9.99);
insert into Produkt(name,gewicht,preis) Values("Obst",1000,3.0);
insert into Produkt(name,gewicht,preis) Values("Blumen",0,2.0);
insert into Produkt(name,gewicht,preis) Values("Milch",1000,1.0);
insert into Produkt(name,gewicht,preis) Values("Wasser",1000,1.0);
insert into Produkt(name,gewicht,preis) Values("Zucker",1000,1.5);
insert into Produkt(name,gewicht,preis) Values("Mehl",2500,2.5);
